/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const StudyChallenge = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'endDate' : IDL.Text,
  'rewardPoints' : IDL.Nat,
  'description' : IDL.Text,
  'goalCount' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileType = IDL.Variant({
  'PDF' : IDL.Null,
  'EPUB' : IDL.Null,
  'Image' : IDL.Null,
  'Banner' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ContentFile = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'name' : IDL.Text,
  'fileBlob' : ExternalBlob,
  'description' : IDL.Opt(IDL.Text),
  'fileType' : FileType,
  'author' : IDL.Opt(IDL.Text),
  'uploadedAt' : Timestamp,
});
export const UserId = IDL.Principal;
export const Audience = IDL.Variant({
  'All' : IDL.Null,
  'CourseAudience' : IDL.Nat,
  'Individual' : UserId,
});
export const DailyQuestion = IDL.Record({
  'id' : IDL.Nat,
  'scheduledDate' : IDL.Text,
  'text' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'audience' : Audience,
});
export const MotivationalMessage = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'audience' : Audience,
  'scheduledAt' : Timestamp,
});
export const PdfFile = IDL.Record({
  'sortOrder' : IDL.Nat,
  'description' : IDL.Opt(IDL.Text),
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'uploadedAt' : IDL.Int,
  'fileKey' : IDL.Text,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'correctIndex' : IDL.Nat,
  'explanation' : IDL.Text,
  'text' : IDL.Text,
  'testId' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const CountdownTimer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'targetDate' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Refunded' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'paymentMethod' : IDL.Text,
  'refundReason' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'date' : Timestamp,
  'amount' : IDL.Nat,
  'courseId' : IDL.Nat,
});
export const VideoFile = IDL.Record({
  'duration' : IDL.Opt(IDL.Text),
  'sortOrder' : IDL.Nat,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'uploadedAt' : IDL.Int,
  'fileKey' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DiscountType = IDL.Variant({
  'Percent' : IDL.Null,
  'Fixed' : IDL.Null,
});
export const Coupon = IDL.Record({
  'id' : IDL.Text,
  'discountValue' : IDL.Float64,
  'expiryDate' : IDL.Opt(IDL.Int),
  'code' : IDL.Text,
  'createdAt' : IDL.Int,
  'discountType' : DiscountType,
  'maxUsage' : IDL.Opt(IDL.Nat),
  'usedCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'courseIds' : IDL.Vec(IDL.Text),
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'thumbnailBlob' : ExternalBlob,
  'moduleCount' : IDL.Nat,
  'price' : IDL.Nat,
  'enrollmentCount' : IDL.Nat,
});
export const VideoType = IDL.Variant({
  'YouTube' : IDL.Null,
  'GoogleDrive' : IDL.Null,
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'moduleId' : IDL.Nat,
  'title' : IDL.Text,
  'pdfUrls' : IDL.Vec(IDL.Text),
  'order' : IDL.Nat,
  'videoType' : VideoType,
  'pdfFiles' : IDL.Vec(PdfFile),
  'isLocked' : IDL.Bool,
  'videoUrl' : IDL.Text,
  'videoFiles' : IDL.Vec(VideoFile),
});
export const MockTest = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'negativeMarking' : IDL.Bool,
  'passingScore' : IDL.Nat,
  'timerMinutes' : IDL.Nat,
  'courseId' : IDL.Nat,
});
export const CourseModule = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'courseId' : IDL.Nat,
});
export const NotificationStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Sent' : IDL.Null,
  'Draft' : IDL.Null,
  'Scheduled' : IDL.Null,
});
export const NotificationAudience = IDL.Variant({
  'All' : IDL.Null,
  'Course' : IDL.Nat,
  'Individual' : UserId,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'status' : NotificationStatus,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'audience' : NotificationAudience,
  'sentAt' : IDL.Opt(Timestamp),
  'ctaUrl' : IDL.Text,
  'scheduledAt' : IDL.Opt(Timestamp),
});
export const TransactionFilter = IDL.Record({
  'status' : IDL.Opt(PaymentStatus),
  'userId' : IDL.Opt(UserId),
  'toDate' : IDL.Opt(Timestamp),
  'fromDate' : IDL.Opt(Timestamp),
});
export const AnalyticsSummary = IDL.Record({
  'activeUsers' : IDL.Nat,
  'newSignupsThisMonth' : IDL.Nat,
  'avgStudyHoursPerUser' : IDL.Float64,
  'courseCompletionRate' : IDL.Float64,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'retentionRate' : IDL.Float64,
  'mrrGrowthPercent' : IDL.Float64,
});
export const AppBranding = IDL.Record({
  'tagline' : IDL.Text,
  'appName' : IDL.Text,
  'primaryColor' : IDL.Text,
  'accentColor' : IDL.Text,
  'updatedAt' : IDL.Int,
  'logoUrl' : IDL.Opt(IDL.Text),
});
export const BankAccountDetails = IDL.Record({
  'ifscCode' : IDL.Text,
  'accountHolderName' : IDL.Text,
  'bankName' : IDL.Text,
  'upiId' : IDL.Opt(IDL.Text),
  'accountNumber' : IDL.Text,
});
export const ConnectedAppSyncStatus = IDL.Variant({
  'Connected' : IDL.Null,
  'Disconnected' : IDL.Null,
  'Syncing' : IDL.Null,
});
export const ConnectedAppInfo = IDL.Record({
  'appName' : IDL.Text,
  'totalStudents' : IDL.Nat,
  'appUrl' : IDL.Text,
  'publishedCourses' : IDL.Nat,
  'lastSyncAt' : IDL.Opt(IDL.Int),
  'totalCourses' : IDL.Nat,
  'syncStatus' : ConnectedAppSyncStatus,
});
export const CouponUsage = IDL.Record({
  'usedAt' : IDL.Int,
  'userId' : IDL.Principal,
  'couponId' : IDL.Text,
  'courseId' : IDL.Text,
});
export const TimeSeriesDataPoint = IDL.Record({
  'value' : IDL.Float64,
  'date' : IDL.Text,
});
export const StudentProgress = IDL.Record({
  'studentId' : UserId,
  'lastActivity' : IDL.Int,
  'videosWatched' : IDL.Nat,
  'completionPercent' : IDL.Float64,
  'enrolledAt' : IDL.Int,
  'lessonsCompleted' : IDL.Vec(IDL.Text),
  'pdfsDownloaded' : IDL.Nat,
  'courseId' : IDL.Text,
});
export const CourseStats = IDL.Record({
  'studentProgress' : IDL.Vec(StudentProgress),
  'avgCompletionPercent' : IDL.Float64,
  'totalRevenue' : IDL.Float64,
  'courseId' : IDL.Text,
  'enrollmentCount' : IDL.Nat,
});
export const HomepageContent = IDL.Record({
  'featuredCourseIds' : IDL.Vec(IDL.Nat),
  'bannerIds' : IDL.Vec(IDL.Nat),
  'announcements' : IDL.Vec(IDL.Text),
});
export const ReferralReward = IDL.Record({
  'rewardPoints' : IDL.Nat,
  'referrerId' : UserId,
});
export const NotificationHistory = IDL.Record({
  'status' : NotificationStatus,
  'sentCount' : IDL.Nat,
});
export const PaymentMethodConfig = IDL.Record({
  'displayName' : IDL.Text,
  'methodId' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'isEnabled' : IDL.Bool,
});
export const RazorpayConfig = IDL.Record({
  'enabled' : IDL.Bool,
  'accountNumber' : IDL.Opt(IDL.Text),
  'keyId' : IDL.Text,
  'keySecret' : IDL.Text,
});
export const RetentionStats = IDL.Record({
  'day7' : IDL.Float64,
  'day30' : IDL.Float64,
});
export const RevenueStats = IDL.Record({
  'mrr' : IDL.Nat,
  'churnedSubscriptions' : IDL.Nat,
  'mtdRevenue' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'activeSubscriptions' : IDL.Nat,
  'transactionCount' : IDL.Nat,
});
export const SyncEndpoint = IDL.Record({
  'url' : IDL.Text,
  'isConnected' : IDL.Bool,
  'validatedAt' : IDL.Opt(IDL.Int),
});
export const TestResult = IDL.Record({
  'userId' : UserId,
  'score' : IDL.Nat,
  'timeTaken' : IDL.Nat,
  'testId' : IDL.Nat,
  'percentage' : IDL.Nat,
  'passed' : IDL.Bool,
});
export const CourseEnrollment = IDL.Record({
  'courseId' : IDL.Nat,
  'enrollmentCount' : IDL.Nat,
});
export const UserStatus = IDL.Variant({
  'Blocked' : IDL.Null,
  'Active' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'status' : UserStatus,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'totalPurchases' : IDL.Nat,
  'phone' : IDL.Text,
  'lastLogin' : Timestamp,
  'enrolledCourses' : IDL.Vec(IDL.Nat),
});
export const UserProgress = IDL.Record({
  'quizScores' : IDL.Vec(IDL.Nat),
  'userId' : UserId,
  'studyTime' : IDL.Nat,
  'completionPercent' : IDL.Nat,
  'courseId' : IDL.Nat,
});
export const WithdrawalStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Processing' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawalStatus,
  'bankDetails' : BankAccountDetails,
  'processedAt' : IDL.Opt(IDL.Int),
  'razorpayPayoutId' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'amount' : IDL.Float64,
  'requestedAt' : IDL.Int,
});
export const WithdrawalStats = IDL.Record({
  'failedRequests' : IDL.Nat,
  'completedRequests' : IDL.Nat,
  'totalWithdrawn' : IDL.Float64,
  'pendingAmount' : IDL.Float64,
});
export const UserAnswer = IDL.Record({
  'questionId' : IDL.Nat,
  'selectedIndex' : IDL.Nat,
});
export const AuditLogEntry = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
});
export const ReferralCodeStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Revoked' : IDL.Null,
});
export const ReferralCode = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReferralCodeStatus,
  'code' : IDL.Text,
  'usageCount' : IDL.Nat,
  'generatedDate' : Timestamp,
  'conversionCount' : IDL.Nat,
});
export const SyncStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Success' : IDL.Null,
});
export const SyncType = IDL.Variant({ 'Auto' : IDL.Null, 'Manual' : IDL.Null });
export const SyncLogEntry = IDL.Record({
  'id' : IDL.Text,
  'status' : SyncStatus,
  'errorMessage' : IDL.Opt(IDL.Text),
  'itemsSynced' : IDL.Nat,
  'syncType' : SyncType,
  'syncedAt' : IDL.Int,
});
export const PaginatedTransactions = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(Transaction),
});
export const WithdrawalFilter = IDL.Record({
  'status' : IDL.Opt(WithdrawalStatus),
});
export const PaginatedWithdrawals = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(WithdrawalRequest),
});
export const ReviewItem = IDL.Record({
  'correctIndex' : IDL.Nat,
  'explanation' : IDL.Text,
  'isCorrect' : IDL.Bool,
  'questionText' : IDL.Text,
  'questionId' : IDL.Nat,
  'userSelectedIndex' : IDL.Opt(IDL.Nat),
  'options' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addChallenge' : IDL.Func([StudyChallenge], [IDL.Nat], []),
  'addContentFile' : IDL.Func([ContentFile], [IDL.Nat], []),
  'addDailyQuestion' : IDL.Func([DailyQuestion], [IDL.Nat], []),
  'addMotivationalMessage' : IDL.Func([MotivationalMessage], [IDL.Nat], []),
  'addPdfFileToLesson' : IDL.Func([IDL.Text, PdfFile], [IDL.Bool], []),
  'addQuestion' : IDL.Func([Question], [IDL.Nat], []),
  'addTimer' : IDL.Func([CountdownTimer], [IDL.Nat], []),
  'addTransaction' : IDL.Func([Transaction], [IDL.Nat], []),
  'addVideoFileToLesson' : IDL.Func([IDL.Text, VideoFile], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelWithdrawalRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'clearSyncLogs' : IDL.Func([], [], []),
  'createCoupon' : IDL.Func([Coupon], [IDL.Bool], []),
  'createCourse' : IDL.Func([Course], [IDL.Nat], []),
  'createLesson' : IDL.Func([Lesson], [IDL.Nat], []),
  'createMockTest' : IDL.Func([MockTest], [IDL.Nat], []),
  'createModule' : IDL.Func([CourseModule], [IDL.Nat], []),
  'createNotification' : IDL.Func([Notification], [IDL.Nat], []),
  'createReferralCode' : IDL.Func([], [IDL.Nat], []),
  'createWithdrawalRequest' : IDL.Func(
      [IDL.Float64, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteChallenge' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteContentFile' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCoupon' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteCourse' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteDailyQuestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteLesson' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMockTest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteModule' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMotivationalMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTimer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'filterTransactions' : IDL.Func(
      [TransactionFilter],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
  'getAppBranding' : IDL.Func([], [AppBranding], ['query']),
  'getBankAccountDetails' : IDL.Func(
      [],
      [IDL.Opt(BankAccountDetails)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChallengeLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getConnectedAppInfo' : IDL.Func([], [ConnectedAppInfo], ['query']),
  'getContentFile' : IDL.Func([IDL.Nat], [IDL.Opt(ContentFile)], ['query']),
  'getCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
  'getCouponUsageHistory' : IDL.Func([IDL.Text], [IDL.Vec(CouponUsage)], []),
  'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getCourseCompletionTimeSeries' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TimeSeriesDataPoint)],
      ['query'],
    ),
  'getCourseStats' : IDL.Func([IDL.Text], [IDL.Opt(CourseStats)], ['query']),
  'getHomepageContent' : IDL.Func([], [HomepageContent], ['query']),
  'getMockTest' : IDL.Func([IDL.Nat], [IDL.Opt(MockTest)], ['query']),
  'getMyRewards' : IDL.Func([], [IDL.Opt(ReferralReward)], ['query']),
  'getNotification' : IDL.Func([IDL.Nat], [IDL.Opt(Notification)], ['query']),
  'getNotificationHistory' : IDL.Func(
      [],
      [IDL.Vec(NotificationHistory)],
      ['query'],
    ),
  'getPaymentMethod' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PaymentMethodConfig)],
      ['query'],
    ),
  'getRazorpayConfig' : IDL.Func([], [IDL.Opt(RazorpayConfig)], ['query']),
  'getRetentionRates' : IDL.Func([], [RetentionStats], ['query']),
  'getRevenueStats' : IDL.Func([], [RevenueStats], ['query']),
  'getRevenueTimeSeries' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TimeSeriesDataPoint)],
      ['query'],
    ),
  'getSentNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getStudentProgress' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudentProgress)],
      ['query'],
    ),
  'getSyncEndpoint' : IDL.Func([], [SyncEndpoint], ['query']),
  'getTestLeaderboard' : IDL.Func([IDL.Nat], [IDL.Vec(TestResult)], ['query']),
  'getTestResult' : IDL.Func(
      [UserId, IDL.Nat],
      [IDL.Opt(TestResult)],
      ['query'],
    ),
  'getTopCoursesByEnrollment' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CourseEnrollment)],
      ['query'],
    ),
  'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getUserDetail' : IDL.Func(
      [UserId],
      [IDL.Opt(IDL.Tuple(UserProfile, IDL.Vec(UserProgress)))],
      ['query'],
    ),
  'getUserProgress' : IDL.Func(
      [UserId, IDL.Nat],
      [IDL.Opt(UserProgress)],
      ['query'],
    ),
  'getUserSignupTimeSeries' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TimeSeriesDataPoint)],
      ['query'],
    ),
  'getWithdrawalRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(WithdrawalRequest)],
      ['query'],
    ),
  'getWithdrawalStats' : IDL.Func([], [WithdrawalStats], ['query']),
  'gradeAndSubmit' : IDL.Func(
      [IDL.Nat, IDL.Vec(UserAnswer), IDL.Nat],
      [TestResult],
      [],
    ),
  'grantCourseAccess' : IDL.Func([UserId, IDL.Nat], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllRewards' : IDL.Func([], [IDL.Vec(ReferralReward)], ['query']),
  'listAuditLog' : IDL.Func([], [IDL.Vec(AuditLogEntry)], ['query']),
  'listChallenges' : IDL.Func([], [IDL.Vec(StudyChallenge)], ['query']),
  'listContentFiles' : IDL.Func([], [IDL.Vec(ContentFile)], ['query']),
  'listCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'listCourseStats' : IDL.Func([], [IDL.Vec(CourseStats)], ['query']),
  'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'listDailyQuestions' : IDL.Func([], [IDL.Vec(DailyQuestion)], ['query']),
  'listFailedTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'listLessons' : IDL.Func([IDL.Nat], [IDL.Vec(Lesson)], ['query']),
  'listMockTests' : IDL.Func([], [IDL.Vec(MockTest)], ['query']),
  'listModules' : IDL.Func([IDL.Nat], [IDL.Vec(CourseModule)], ['query']),
  'listMotivationalMessages' : IDL.Func(
      [],
      [IDL.Vec(MotivationalMessage)],
      ['query'],
    ),
  'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'listPaymentMethods' : IDL.Func(
      [],
      [IDL.Vec(PaymentMethodConfig)],
      ['query'],
    ),
  'listQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
  'listReferralCodes' : IDL.Func([], [IDL.Vec(ReferralCode)], ['query']),
  'listSyncLogs' : IDL.Func([], [IDL.Vec(SyncLogEntry)], ['query']),
  'listTimers' : IDL.Func([], [IDL.Vec(CountdownTimer)], ['query']),
  'listTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'listTransactionsPaginated' : IDL.Func(
      [TransactionFilter, IDL.Nat, IDL.Nat],
      [PaginatedTransactions],
      ['query'],
    ),
  'listUserProgress' : IDL.Func([UserId], [IDL.Vec(UserProgress)], ['query']),
  'listUserTransactions' : IDL.Func(
      [UserId],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'listUsers' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(UserStatus), IDL.Nat, IDL.Nat],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'listWithdrawalRequests' : IDL.Func(
      [WithdrawalFilter, IDL.Nat, IDL.Nat],
      [PaginatedWithdrawals],
      ['query'],
    ),
  'publishCourse' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'recordChallengeCompletion' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'recordPdfDownload' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'recordSyncLog' : IDL.Func([SyncLogEntry], [], []),
  'recordVideoView' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'refundTransaction' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'regenerateReferralCode' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
  'removePdfFileFromLesson' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'removeVideoFileFromLesson' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'reorderLessonFiles' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'reviewTestAnswers' : IDL.Func(
      [IDL.Nat, IDL.Vec(UserAnswer)],
      [IDL.Vec(ReviewItem)],
      ['query'],
    ),
  'revokeCourseAccess' : IDL.Func([UserId, IDL.Nat], [IDL.Bool], []),
  'revokeReferralCode' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'sendNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'setAppBranding' : IDL.Func([AppBranding], [], []),
  'setBankAccountDetails' : IDL.Func([BankAccountDetails], [], []),
  'setContentFilePublished' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'setHomepageContent' : IDL.Func([HomepageContent], [], []),
  'setPaymentMethodEnabled' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
  'setRazorpayConfig' : IDL.Func([RazorpayConfig], [], []),
  'setSyncEndpoint' : IDL.Func([IDL.Text], [], []),
  'setUserStatus' : IDL.Func([UserId, UserStatus], [IDL.Bool], []),
  'submitTestResult' : IDL.Func([TestResult], [], []),
  'toggleCouponStatus' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'topReferrers' : IDL.Func([], [IDL.Vec(ReferralReward)], ['query']),
  'updateChallenge' : IDL.Func([StudyChallenge], [IDL.Bool], []),
  'updateConnectedAppInfo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateContentFile' : IDL.Func([ContentFile], [IDL.Bool], []),
  'updateCoupon' : IDL.Func([Coupon], [IDL.Bool], []),
  'updateCourse' : IDL.Func([Course], [IDL.Bool], []),
  'updateDailyQuestion' : IDL.Func([DailyQuestion], [IDL.Bool], []),
  'updateLesson' : IDL.Func([Lesson], [IDL.Bool], []),
  'updateMockTest' : IDL.Func([MockTest], [IDL.Bool], []),
  'updateModule' : IDL.Func([CourseModule], [IDL.Bool], []),
  'updateNotification' : IDL.Func([Notification], [IDL.Bool], []),
  'updateQuestion' : IDL.Func([Question], [IDL.Bool], []),
  'updateTransactionStatus' : IDL.Func(
      [IDL.Nat, PaymentStatus],
      [IDL.Bool],
      [],
    ),
  'updateWithdrawalStatus' : IDL.Func(
      [IDL.Nat, WithdrawalStatus, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'upsertPaymentMethod' : IDL.Func([PaymentMethodConfig], [], []),
  'upsertProgress' : IDL.Func([UserProgress], [], []),
  'upsertUser' : IDL.Func([UserProfile], [], []),
  'useCoupon' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'useReferralCode' : IDL.Func([IDL.Text, UserId], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const StudyChallenge = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'endDate' : IDL.Text,
    'rewardPoints' : IDL.Nat,
    'description' : IDL.Text,
    'goalCount' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileType = IDL.Variant({
    'PDF' : IDL.Null,
    'EPUB' : IDL.Null,
    'Image' : IDL.Null,
    'Banner' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ContentFile = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'name' : IDL.Text,
    'fileBlob' : ExternalBlob,
    'description' : IDL.Opt(IDL.Text),
    'fileType' : FileType,
    'author' : IDL.Opt(IDL.Text),
    'uploadedAt' : Timestamp,
  });
  const UserId = IDL.Principal;
  const Audience = IDL.Variant({
    'All' : IDL.Null,
    'CourseAudience' : IDL.Nat,
    'Individual' : UserId,
  });
  const DailyQuestion = IDL.Record({
    'id' : IDL.Nat,
    'scheduledDate' : IDL.Text,
    'text' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'audience' : Audience,
  });
  const MotivationalMessage = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'audience' : Audience,
    'scheduledAt' : Timestamp,
  });
  const PdfFile = IDL.Record({
    'sortOrder' : IDL.Nat,
    'description' : IDL.Opt(IDL.Text),
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'uploadedAt' : IDL.Int,
    'fileKey' : IDL.Text,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'correctIndex' : IDL.Nat,
    'explanation' : IDL.Text,
    'text' : IDL.Text,
    'testId' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const CountdownTimer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'targetDate' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Refunded' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'paymentMethod' : IDL.Text,
    'refundReason' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'date' : Timestamp,
    'amount' : IDL.Nat,
    'courseId' : IDL.Nat,
  });
  const VideoFile = IDL.Record({
    'duration' : IDL.Opt(IDL.Text),
    'sortOrder' : IDL.Nat,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'uploadedAt' : IDL.Int,
    'fileKey' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DiscountType = IDL.Variant({
    'Percent' : IDL.Null,
    'Fixed' : IDL.Null,
  });
  const Coupon = IDL.Record({
    'id' : IDL.Text,
    'discountValue' : IDL.Float64,
    'expiryDate' : IDL.Opt(IDL.Int),
    'code' : IDL.Text,
    'createdAt' : IDL.Int,
    'discountType' : DiscountType,
    'maxUsage' : IDL.Opt(IDL.Nat),
    'usedCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'courseIds' : IDL.Vec(IDL.Text),
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'thumbnailBlob' : ExternalBlob,
    'moduleCount' : IDL.Nat,
    'price' : IDL.Nat,
    'enrollmentCount' : IDL.Nat,
  });
  const VideoType = IDL.Variant({
    'YouTube' : IDL.Null,
    'GoogleDrive' : IDL.Null,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'moduleId' : IDL.Nat,
    'title' : IDL.Text,
    'pdfUrls' : IDL.Vec(IDL.Text),
    'order' : IDL.Nat,
    'videoType' : VideoType,
    'pdfFiles' : IDL.Vec(PdfFile),
    'isLocked' : IDL.Bool,
    'videoUrl' : IDL.Text,
    'videoFiles' : IDL.Vec(VideoFile),
  });
  const MockTest = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'negativeMarking' : IDL.Bool,
    'passingScore' : IDL.Nat,
    'timerMinutes' : IDL.Nat,
    'courseId' : IDL.Nat,
  });
  const CourseModule = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'courseId' : IDL.Nat,
  });
  const NotificationStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Sent' : IDL.Null,
    'Draft' : IDL.Null,
    'Scheduled' : IDL.Null,
  });
  const NotificationAudience = IDL.Variant({
    'All' : IDL.Null,
    'Course' : IDL.Nat,
    'Individual' : UserId,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'status' : NotificationStatus,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'audience' : NotificationAudience,
    'sentAt' : IDL.Opt(Timestamp),
    'ctaUrl' : IDL.Text,
    'scheduledAt' : IDL.Opt(Timestamp),
  });
  const TransactionFilter = IDL.Record({
    'status' : IDL.Opt(PaymentStatus),
    'userId' : IDL.Opt(UserId),
    'toDate' : IDL.Opt(Timestamp),
    'fromDate' : IDL.Opt(Timestamp),
  });
  const AnalyticsSummary = IDL.Record({
    'activeUsers' : IDL.Nat,
    'newSignupsThisMonth' : IDL.Nat,
    'avgStudyHoursPerUser' : IDL.Float64,
    'courseCompletionRate' : IDL.Float64,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'retentionRate' : IDL.Float64,
    'mrrGrowthPercent' : IDL.Float64,
  });
  const AppBranding = IDL.Record({
    'tagline' : IDL.Text,
    'appName' : IDL.Text,
    'primaryColor' : IDL.Text,
    'accentColor' : IDL.Text,
    'updatedAt' : IDL.Int,
    'logoUrl' : IDL.Opt(IDL.Text),
  });
  const BankAccountDetails = IDL.Record({
    'ifscCode' : IDL.Text,
    'accountHolderName' : IDL.Text,
    'bankName' : IDL.Text,
    'upiId' : IDL.Opt(IDL.Text),
    'accountNumber' : IDL.Text,
  });
  const ConnectedAppSyncStatus = IDL.Variant({
    'Connected' : IDL.Null,
    'Disconnected' : IDL.Null,
    'Syncing' : IDL.Null,
  });
  const ConnectedAppInfo = IDL.Record({
    'appName' : IDL.Text,
    'totalStudents' : IDL.Nat,
    'appUrl' : IDL.Text,
    'publishedCourses' : IDL.Nat,
    'lastSyncAt' : IDL.Opt(IDL.Int),
    'totalCourses' : IDL.Nat,
    'syncStatus' : ConnectedAppSyncStatus,
  });
  const CouponUsage = IDL.Record({
    'usedAt' : IDL.Int,
    'userId' : IDL.Principal,
    'couponId' : IDL.Text,
    'courseId' : IDL.Text,
  });
  const TimeSeriesDataPoint = IDL.Record({
    'value' : IDL.Float64,
    'date' : IDL.Text,
  });
  const StudentProgress = IDL.Record({
    'studentId' : UserId,
    'lastActivity' : IDL.Int,
    'videosWatched' : IDL.Nat,
    'completionPercent' : IDL.Float64,
    'enrolledAt' : IDL.Int,
    'lessonsCompleted' : IDL.Vec(IDL.Text),
    'pdfsDownloaded' : IDL.Nat,
    'courseId' : IDL.Text,
  });
  const CourseStats = IDL.Record({
    'studentProgress' : IDL.Vec(StudentProgress),
    'avgCompletionPercent' : IDL.Float64,
    'totalRevenue' : IDL.Float64,
    'courseId' : IDL.Text,
    'enrollmentCount' : IDL.Nat,
  });
  const HomepageContent = IDL.Record({
    'featuredCourseIds' : IDL.Vec(IDL.Nat),
    'bannerIds' : IDL.Vec(IDL.Nat),
    'announcements' : IDL.Vec(IDL.Text),
  });
  const ReferralReward = IDL.Record({
    'rewardPoints' : IDL.Nat,
    'referrerId' : UserId,
  });
  const NotificationHistory = IDL.Record({
    'status' : NotificationStatus,
    'sentCount' : IDL.Nat,
  });
  const PaymentMethodConfig = IDL.Record({
    'displayName' : IDL.Text,
    'methodId' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'isEnabled' : IDL.Bool,
  });
  const RazorpayConfig = IDL.Record({
    'enabled' : IDL.Bool,
    'accountNumber' : IDL.Opt(IDL.Text),
    'keyId' : IDL.Text,
    'keySecret' : IDL.Text,
  });
  const RetentionStats = IDL.Record({
    'day7' : IDL.Float64,
    'day30' : IDL.Float64,
  });
  const RevenueStats = IDL.Record({
    'mrr' : IDL.Nat,
    'churnedSubscriptions' : IDL.Nat,
    'mtdRevenue' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'activeSubscriptions' : IDL.Nat,
    'transactionCount' : IDL.Nat,
  });
  const SyncEndpoint = IDL.Record({
    'url' : IDL.Text,
    'isConnected' : IDL.Bool,
    'validatedAt' : IDL.Opt(IDL.Int),
  });
  const TestResult = IDL.Record({
    'userId' : UserId,
    'score' : IDL.Nat,
    'timeTaken' : IDL.Nat,
    'testId' : IDL.Nat,
    'percentage' : IDL.Nat,
    'passed' : IDL.Bool,
  });
  const CourseEnrollment = IDL.Record({
    'courseId' : IDL.Nat,
    'enrollmentCount' : IDL.Nat,
  });
  const UserStatus = IDL.Variant({ 'Blocked' : IDL.Null, 'Active' : IDL.Null });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'status' : UserStatus,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'totalPurchases' : IDL.Nat,
    'phone' : IDL.Text,
    'lastLogin' : Timestamp,
    'enrolledCourses' : IDL.Vec(IDL.Nat),
  });
  const UserProgress = IDL.Record({
    'quizScores' : IDL.Vec(IDL.Nat),
    'userId' : UserId,
    'studyTime' : IDL.Nat,
    'completionPercent' : IDL.Nat,
    'courseId' : IDL.Nat,
  });
  const WithdrawalStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Processing' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawalStatus,
    'bankDetails' : BankAccountDetails,
    'processedAt' : IDL.Opt(IDL.Int),
    'razorpayPayoutId' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'amount' : IDL.Float64,
    'requestedAt' : IDL.Int,
  });
  const WithdrawalStats = IDL.Record({
    'failedRequests' : IDL.Nat,
    'completedRequests' : IDL.Nat,
    'totalWithdrawn' : IDL.Float64,
    'pendingAmount' : IDL.Float64,
  });
  const UserAnswer = IDL.Record({
    'questionId' : IDL.Nat,
    'selectedIndex' : IDL.Nat,
  });
  const AuditLogEntry = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'userId' : UserId,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
  });
  const ReferralCodeStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Revoked' : IDL.Null,
  });
  const ReferralCode = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReferralCodeStatus,
    'code' : IDL.Text,
    'usageCount' : IDL.Nat,
    'generatedDate' : Timestamp,
    'conversionCount' : IDL.Nat,
  });
  const SyncStatus = IDL.Variant({ 'Failed' : IDL.Null, 'Success' : IDL.Null });
  const SyncType = IDL.Variant({ 'Auto' : IDL.Null, 'Manual' : IDL.Null });
  const SyncLogEntry = IDL.Record({
    'id' : IDL.Text,
    'status' : SyncStatus,
    'errorMessage' : IDL.Opt(IDL.Text),
    'itemsSynced' : IDL.Nat,
    'syncType' : SyncType,
    'syncedAt' : IDL.Int,
  });
  const PaginatedTransactions = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(Transaction),
  });
  const WithdrawalFilter = IDL.Record({ 'status' : IDL.Opt(WithdrawalStatus) });
  const PaginatedWithdrawals = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(WithdrawalRequest),
  });
  const ReviewItem = IDL.Record({
    'correctIndex' : IDL.Nat,
    'explanation' : IDL.Text,
    'isCorrect' : IDL.Bool,
    'questionText' : IDL.Text,
    'questionId' : IDL.Nat,
    'userSelectedIndex' : IDL.Opt(IDL.Nat),
    'options' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addChallenge' : IDL.Func([StudyChallenge], [IDL.Nat], []),
    'addContentFile' : IDL.Func([ContentFile], [IDL.Nat], []),
    'addDailyQuestion' : IDL.Func([DailyQuestion], [IDL.Nat], []),
    'addMotivationalMessage' : IDL.Func([MotivationalMessage], [IDL.Nat], []),
    'addPdfFileToLesson' : IDL.Func([IDL.Text, PdfFile], [IDL.Bool], []),
    'addQuestion' : IDL.Func([Question], [IDL.Nat], []),
    'addTimer' : IDL.Func([CountdownTimer], [IDL.Nat], []),
    'addTransaction' : IDL.Func([Transaction], [IDL.Nat], []),
    'addVideoFileToLesson' : IDL.Func([IDL.Text, VideoFile], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelWithdrawalRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'clearSyncLogs' : IDL.Func([], [], []),
    'createCoupon' : IDL.Func([Coupon], [IDL.Bool], []),
    'createCourse' : IDL.Func([Course], [IDL.Nat], []),
    'createLesson' : IDL.Func([Lesson], [IDL.Nat], []),
    'createMockTest' : IDL.Func([MockTest], [IDL.Nat], []),
    'createModule' : IDL.Func([CourseModule], [IDL.Nat], []),
    'createNotification' : IDL.Func([Notification], [IDL.Nat], []),
    'createReferralCode' : IDL.Func([], [IDL.Nat], []),
    'createWithdrawalRequest' : IDL.Func(
        [IDL.Float64, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteChallenge' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteContentFile' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCoupon' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteCourse' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteDailyQuestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteLesson' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMockTest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteModule' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMotivationalMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTimer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'filterTransactions' : IDL.Func(
        [TransactionFilter],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
    'getAppBranding' : IDL.Func([], [AppBranding], ['query']),
    'getBankAccountDetails' : IDL.Func(
        [],
        [IDL.Opt(BankAccountDetails)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChallengeLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getConnectedAppInfo' : IDL.Func([], [ConnectedAppInfo], ['query']),
    'getContentFile' : IDL.Func([IDL.Nat], [IDL.Opt(ContentFile)], ['query']),
    'getCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
    'getCouponUsageHistory' : IDL.Func([IDL.Text], [IDL.Vec(CouponUsage)], []),
    'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getCourseCompletionTimeSeries' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TimeSeriesDataPoint)],
        ['query'],
      ),
    'getCourseStats' : IDL.Func([IDL.Text], [IDL.Opt(CourseStats)], ['query']),
    'getHomepageContent' : IDL.Func([], [HomepageContent], ['query']),
    'getMockTest' : IDL.Func([IDL.Nat], [IDL.Opt(MockTest)], ['query']),
    'getMyRewards' : IDL.Func([], [IDL.Opt(ReferralReward)], ['query']),
    'getNotification' : IDL.Func([IDL.Nat], [IDL.Opt(Notification)], ['query']),
    'getNotificationHistory' : IDL.Func(
        [],
        [IDL.Vec(NotificationHistory)],
        ['query'],
      ),
    'getPaymentMethod' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PaymentMethodConfig)],
        ['query'],
      ),
    'getRazorpayConfig' : IDL.Func([], [IDL.Opt(RazorpayConfig)], ['query']),
    'getRetentionRates' : IDL.Func([], [RetentionStats], ['query']),
    'getRevenueStats' : IDL.Func([], [RevenueStats], ['query']),
    'getRevenueTimeSeries' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TimeSeriesDataPoint)],
        ['query'],
      ),
    'getSentNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getStudentProgress' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudentProgress)],
        ['query'],
      ),
    'getSyncEndpoint' : IDL.Func([], [SyncEndpoint], ['query']),
    'getTestLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TestResult)],
        ['query'],
      ),
    'getTestResult' : IDL.Func(
        [UserId, IDL.Nat],
        [IDL.Opt(TestResult)],
        ['query'],
      ),
    'getTopCoursesByEnrollment' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CourseEnrollment)],
        ['query'],
      ),
    'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getUserDetail' : IDL.Func(
        [UserId],
        [IDL.Opt(IDL.Tuple(UserProfile, IDL.Vec(UserProgress)))],
        ['query'],
      ),
    'getUserProgress' : IDL.Func(
        [UserId, IDL.Nat],
        [IDL.Opt(UserProgress)],
        ['query'],
      ),
    'getUserSignupTimeSeries' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TimeSeriesDataPoint)],
        ['query'],
      ),
    'getWithdrawalRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(WithdrawalRequest)],
        ['query'],
      ),
    'getWithdrawalStats' : IDL.Func([], [WithdrawalStats], ['query']),
    'gradeAndSubmit' : IDL.Func(
        [IDL.Nat, IDL.Vec(UserAnswer), IDL.Nat],
        [TestResult],
        [],
      ),
    'grantCourseAccess' : IDL.Func([UserId, IDL.Nat], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllRewards' : IDL.Func([], [IDL.Vec(ReferralReward)], ['query']),
    'listAuditLog' : IDL.Func([], [IDL.Vec(AuditLogEntry)], ['query']),
    'listChallenges' : IDL.Func([], [IDL.Vec(StudyChallenge)], ['query']),
    'listContentFiles' : IDL.Func([], [IDL.Vec(ContentFile)], ['query']),
    'listCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'listCourseStats' : IDL.Func([], [IDL.Vec(CourseStats)], ['query']),
    'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'listDailyQuestions' : IDL.Func([], [IDL.Vec(DailyQuestion)], ['query']),
    'listFailedTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'listLessons' : IDL.Func([IDL.Nat], [IDL.Vec(Lesson)], ['query']),
    'listMockTests' : IDL.Func([], [IDL.Vec(MockTest)], ['query']),
    'listModules' : IDL.Func([IDL.Nat], [IDL.Vec(CourseModule)], ['query']),
    'listMotivationalMessages' : IDL.Func(
        [],
        [IDL.Vec(MotivationalMessage)],
        ['query'],
      ),
    'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'listPaymentMethods' : IDL.Func(
        [],
        [IDL.Vec(PaymentMethodConfig)],
        ['query'],
      ),
    'listQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
    'listReferralCodes' : IDL.Func([], [IDL.Vec(ReferralCode)], ['query']),
    'listSyncLogs' : IDL.Func([], [IDL.Vec(SyncLogEntry)], ['query']),
    'listTimers' : IDL.Func([], [IDL.Vec(CountdownTimer)], ['query']),
    'listTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'listTransactionsPaginated' : IDL.Func(
        [TransactionFilter, IDL.Nat, IDL.Nat],
        [PaginatedTransactions],
        ['query'],
      ),
    'listUserProgress' : IDL.Func([UserId], [IDL.Vec(UserProgress)], ['query']),
    'listUserTransactions' : IDL.Func(
        [UserId],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'listUsers' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(UserStatus), IDL.Nat, IDL.Nat],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'listWithdrawalRequests' : IDL.Func(
        [WithdrawalFilter, IDL.Nat, IDL.Nat],
        [PaginatedWithdrawals],
        ['query'],
      ),
    'publishCourse' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'recordChallengeCompletion' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'recordPdfDownload' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'recordSyncLog' : IDL.Func([SyncLogEntry], [], []),
    'recordVideoView' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'refundTransaction' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'regenerateReferralCode' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], []),
    'removePdfFileFromLesson' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'removeVideoFileFromLesson' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'reorderLessonFiles' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'reviewTestAnswers' : IDL.Func(
        [IDL.Nat, IDL.Vec(UserAnswer)],
        [IDL.Vec(ReviewItem)],
        ['query'],
      ),
    'revokeCourseAccess' : IDL.Func([UserId, IDL.Nat], [IDL.Bool], []),
    'revokeReferralCode' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'sendNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'setAppBranding' : IDL.Func([AppBranding], [], []),
    'setBankAccountDetails' : IDL.Func([BankAccountDetails], [], []),
    'setContentFilePublished' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'setHomepageContent' : IDL.Func([HomepageContent], [], []),
    'setPaymentMethodEnabled' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
    'setRazorpayConfig' : IDL.Func([RazorpayConfig], [], []),
    'setSyncEndpoint' : IDL.Func([IDL.Text], [], []),
    'setUserStatus' : IDL.Func([UserId, UserStatus], [IDL.Bool], []),
    'submitTestResult' : IDL.Func([TestResult], [], []),
    'toggleCouponStatus' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'topReferrers' : IDL.Func([], [IDL.Vec(ReferralReward)], ['query']),
    'updateChallenge' : IDL.Func([StudyChallenge], [IDL.Bool], []),
    'updateConnectedAppInfo' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateContentFile' : IDL.Func([ContentFile], [IDL.Bool], []),
    'updateCoupon' : IDL.Func([Coupon], [IDL.Bool], []),
    'updateCourse' : IDL.Func([Course], [IDL.Bool], []),
    'updateDailyQuestion' : IDL.Func([DailyQuestion], [IDL.Bool], []),
    'updateLesson' : IDL.Func([Lesson], [IDL.Bool], []),
    'updateMockTest' : IDL.Func([MockTest], [IDL.Bool], []),
    'updateModule' : IDL.Func([CourseModule], [IDL.Bool], []),
    'updateNotification' : IDL.Func([Notification], [IDL.Bool], []),
    'updateQuestion' : IDL.Func([Question], [IDL.Bool], []),
    'updateTransactionStatus' : IDL.Func(
        [IDL.Nat, PaymentStatus],
        [IDL.Bool],
        [],
      ),
    'updateWithdrawalStatus' : IDL.Func(
        [IDL.Nat, WithdrawalStatus, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'upsertPaymentMethod' : IDL.Func([PaymentMethodConfig], [], []),
    'upsertProgress' : IDL.Func([UserProgress], [], []),
    'upsertUser' : IDL.Func([UserProfile], [], []),
    'useCoupon' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'useReferralCode' : IDL.Func([IDL.Text, UserId], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };