/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'activeUsers' : bigint,
  'newSignupsThisMonth' : bigint,
  'avgStudyHoursPerUser' : number,
  'courseCompletionRate' : number,
  'totalUsers' : bigint,
  'totalRevenue' : bigint,
  'retentionRate' : number,
  'mrrGrowthPercent' : number,
}
export interface AppBranding {
  'tagline' : string,
  'appName' : string,
  'primaryColor' : string,
  'accentColor' : string,
  'updatedAt' : bigint,
  'logoUrl' : [] | [string],
}
export type Audience = { 'All' : null } |
  { 'CourseAudience' : bigint } |
  { 'Individual' : UserId };
export interface AuditLogEntry {
  'id' : bigint,
  'action' : string,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'details' : string,
}
export interface BankAccountDetails {
  'ifscCode' : string,
  'accountHolderName' : string,
  'bankName' : string,
  'upiId' : [] | [string],
  'accountNumber' : string,
}
export interface ConnectedAppInfo {
  'appName' : string,
  'totalStudents' : bigint,
  'appUrl' : string,
  'publishedCourses' : bigint,
  'lastSyncAt' : [] | [bigint],
  'totalCourses' : bigint,
  'syncStatus' : ConnectedAppSyncStatus,
}
export type ConnectedAppSyncStatus = { 'Connected' : null } |
  { 'Disconnected' : null } |
  { 'Syncing' : null };
export interface ContentFile {
  'id' : bigint,
  'title' : string,
  'isPublished' : boolean,
  'name' : string,
  'fileBlob' : ExternalBlob,
  'description' : [] | [string],
  'fileType' : FileType,
  'author' : [] | [string],
  'uploadedAt' : Timestamp,
}
export interface CountdownTimer {
  'id' : bigint,
  'name' : string,
  'targetDate' : string,
}
export interface Coupon {
  'id' : string,
  'discountValue' : number,
  'expiryDate' : [] | [bigint],
  'code' : string,
  'createdAt' : bigint,
  'discountType' : DiscountType,
  'maxUsage' : [] | [bigint],
  'usedCount' : bigint,
  'isActive' : boolean,
  'courseIds' : Array<string>,
}
export interface CouponUsage {
  'usedAt' : bigint,
  'userId' : Principal,
  'couponId' : string,
  'courseId' : string,
}
export interface Course {
  'id' : bigint,
  'title' : string,
  'isPublished' : boolean,
  'createdAt' : Timestamp,
  'description' : string,
  'isFree' : boolean,
  'thumbnailBlob' : ExternalBlob,
  'moduleCount' : bigint,
  'price' : bigint,
  'enrollmentCount' : bigint,
}
export interface CourseEnrollment {
  'courseId' : bigint,
  'enrollmentCount' : bigint,
}
export interface CourseModule {
  'id' : bigint,
  'title' : string,
  'order' : bigint,
  'courseId' : bigint,
}
export interface CourseStats {
  'studentProgress' : Array<StudentProgress>,
  'avgCompletionPercent' : number,
  'totalRevenue' : number,
  'courseId' : string,
  'enrollmentCount' : bigint,
}
export interface DailyQuestion {
  'id' : bigint,
  'scheduledDate' : string,
  'text' : string,
  'correctAnswer' : string,
  'audience' : Audience,
}
export type DiscountType = { 'Percent' : null } |
  { 'Fixed' : null };
export type ExternalBlob = Uint8Array;
export type FileType = { 'PDF' : null } |
  { 'EPUB' : null } |
  { 'Image' : null } |
  { 'Banner' : null };
export interface HomepageContent {
  'featuredCourseIds' : Array<bigint>,
  'bannerIds' : Array<bigint>,
  'announcements' : Array<string>,
}
export interface Lesson {
  'id' : bigint,
  'moduleId' : bigint,
  'title' : string,
  'pdfUrls' : Array<string>,
  'order' : bigint,
  'videoType' : VideoType,
  'pdfFiles' : Array<PdfFile>,
  'isLocked' : boolean,
  'videoUrl' : string,
  'videoFiles' : Array<VideoFile>,
}
export interface MockTest {
  'id' : bigint,
  'title' : string,
  'negativeMarking' : boolean,
  'passingScore' : bigint,
  'timerMinutes' : bigint,
  'courseId' : bigint,
}
export interface MotivationalMessage {
  'id' : bigint,
  'text' : string,
  'audience' : Audience,
  'scheduledAt' : Timestamp,
}
export interface Notification {
  'id' : bigint,
  'status' : NotificationStatus,
  'title' : string,
  'body' : string,
  'audience' : NotificationAudience,
  'sentAt' : [] | [Timestamp],
  'ctaUrl' : string,
  'scheduledAt' : [] | [Timestamp],
}
export type NotificationAudience = { 'All' : null } |
  { 'Course' : bigint } |
  { 'Individual' : UserId };
export interface NotificationHistory {
  'status' : NotificationStatus,
  'sentCount' : bigint,
}
export type NotificationStatus = { 'Failed' : null } |
  { 'Sent' : null } |
  { 'Draft' : null } |
  { 'Scheduled' : null };
export interface PaginatedTransactions {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<Transaction>,
}
export interface PaginatedWithdrawals {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<WithdrawalRequest>,
}
export interface PaymentMethodConfig {
  'displayName' : string,
  'methodId' : string,
  'lastUpdated' : bigint,
  'isEnabled' : boolean,
}
export type PaymentStatus = { 'Failed' : null } |
  { 'Refunded' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface PdfFile {
  'sortOrder' : bigint,
  'description' : [] | [string],
  'fileName' : string,
  'fileSize' : bigint,
  'uploadedAt' : bigint,
  'fileKey' : string,
}
export interface Question {
  'id' : bigint,
  'correctIndex' : bigint,
  'explanation' : string,
  'text' : string,
  'testId' : bigint,
  'options' : Array<string>,
}
export interface RazorpayConfig {
  'enabled' : boolean,
  'accountNumber' : [] | [string],
  'keyId' : string,
  'keySecret' : string,
}
export interface ReferralCode {
  'id' : bigint,
  'status' : ReferralCodeStatus,
  'code' : string,
  'usageCount' : bigint,
  'generatedDate' : Timestamp,
  'conversionCount' : bigint,
}
export type ReferralCodeStatus = { 'Active' : null } |
  { 'Revoked' : null };
export interface ReferralReward {
  'rewardPoints' : bigint,
  'referrerId' : UserId,
}
export interface RetentionStats { 'day7' : number, 'day30' : number }
export interface RevenueStats {
  'mrr' : bigint,
  'churnedSubscriptions' : bigint,
  'mtdRevenue' : bigint,
  'totalRevenue' : bigint,
  'activeSubscriptions' : bigint,
  'transactionCount' : bigint,
}
export interface ReviewItem {
  'correctIndex' : bigint,
  'explanation' : string,
  'isCorrect' : boolean,
  'questionText' : string,
  'questionId' : bigint,
  'userSelectedIndex' : [] | [bigint],
  'options' : Array<string>,
}
export interface StudentProgress {
  'studentId' : UserId,
  'lastActivity' : bigint,
  'videosWatched' : bigint,
  'completionPercent' : number,
  'enrolledAt' : bigint,
  'lessonsCompleted' : Array<string>,
  'pdfsDownloaded' : bigint,
  'courseId' : string,
}
export interface StudyChallenge {
  'id' : bigint,
  'title' : string,
  'endDate' : string,
  'rewardPoints' : bigint,
  'description' : string,
  'goalCount' : bigint,
}
export interface SyncEndpoint {
  'url' : string,
  'isConnected' : boolean,
  'validatedAt' : [] | [bigint],
}
export interface SyncLogEntry {
  'id' : string,
  'status' : SyncStatus,
  'errorMessage' : [] | [string],
  'itemsSynced' : bigint,
  'syncType' : SyncType,
  'syncedAt' : bigint,
}
export type SyncStatus = { 'Failed' : null } |
  { 'Success' : null };
export type SyncType = { 'Auto' : null } |
  { 'Manual' : null };
export interface TestResult {
  'userId' : UserId,
  'score' : bigint,
  'timeTaken' : bigint,
  'testId' : bigint,
  'percentage' : bigint,
  'passed' : boolean,
}
export interface TimeSeriesDataPoint { 'value' : number, 'date' : string }
export type Timestamp = bigint;
export interface Transaction {
  'id' : bigint,
  'status' : PaymentStatus,
  'paymentMethod' : string,
  'refundReason' : [] | [string],
  'userId' : UserId,
  'date' : Timestamp,
  'amount' : bigint,
  'courseId' : bigint,
}
export interface TransactionFilter {
  'status' : [] | [PaymentStatus],
  'userId' : [] | [UserId],
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
}
export interface UserAnswer { 'questionId' : bigint, 'selectedIndex' : bigint }
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'status' : UserStatus,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'totalPurchases' : bigint,
  'phone' : string,
  'lastLogin' : Timestamp,
  'enrolledCourses' : Array<bigint>,
}
export interface UserProgress {
  'quizScores' : Array<bigint>,
  'userId' : UserId,
  'studyTime' : bigint,
  'completionPercent' : bigint,
  'courseId' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'Blocked' : null } |
  { 'Active' : null };
export interface VideoFile {
  'duration' : [] | [string],
  'sortOrder' : bigint,
  'fileName' : string,
  'fileSize' : bigint,
  'uploadedAt' : bigint,
  'fileKey' : string,
}
export type VideoType = { 'YouTube' : null } |
  { 'GoogleDrive' : null };
export interface WithdrawalFilter { 'status' : [] | [WithdrawalStatus] }
export interface WithdrawalRequest {
  'id' : bigint,
  'status' : WithdrawalStatus,
  'bankDetails' : BankAccountDetails,
  'processedAt' : [] | [bigint],
  'razorpayPayoutId' : [] | [string],
  'notes' : [] | [string],
  'amount' : number,
  'requestedAt' : bigint,
}
export interface WithdrawalStats {
  'failedRequests' : bigint,
  'completedRequests' : bigint,
  'totalWithdrawn' : number,
  'pendingAmount' : number,
}
export type WithdrawalStatus = { 'Failed' : null } |
  { 'Processing' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addChallenge' : ActorMethod<[StudyChallenge], bigint>,
  'addContentFile' : ActorMethod<[ContentFile], bigint>,
  'addDailyQuestion' : ActorMethod<[DailyQuestion], bigint>,
  'addMotivationalMessage' : ActorMethod<[MotivationalMessage], bigint>,
  'addPdfFileToLesson' : ActorMethod<[string, PdfFile], boolean>,
  'addQuestion' : ActorMethod<[Question], bigint>,
  'addTimer' : ActorMethod<[CountdownTimer], bigint>,
  'addTransaction' : ActorMethod<[Transaction], bigint>,
  'addVideoFileToLesson' : ActorMethod<[string, VideoFile], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelWithdrawalRequest' : ActorMethod<[bigint], boolean>,
  'clearSyncLogs' : ActorMethod<[], undefined>,
  'createCoupon' : ActorMethod<[Coupon], boolean>,
  'createCourse' : ActorMethod<[Course], bigint>,
  'createLesson' : ActorMethod<[Lesson], bigint>,
  'createMockTest' : ActorMethod<[MockTest], bigint>,
  'createModule' : ActorMethod<[CourseModule], bigint>,
  'createNotification' : ActorMethod<[Notification], bigint>,
  'createReferralCode' : ActorMethod<[], bigint>,
  'createWithdrawalRequest' : ActorMethod<[number, [] | [string]], bigint>,
  'deleteChallenge' : ActorMethod<[bigint], boolean>,
  'deleteContentFile' : ActorMethod<[bigint], boolean>,
  'deleteCoupon' : ActorMethod<[string], boolean>,
  'deleteCourse' : ActorMethod<[bigint], boolean>,
  'deleteDailyQuestion' : ActorMethod<[bigint], boolean>,
  'deleteLesson' : ActorMethod<[bigint], boolean>,
  'deleteMockTest' : ActorMethod<[bigint], boolean>,
  'deleteModule' : ActorMethod<[bigint], boolean>,
  'deleteMotivationalMessage' : ActorMethod<[bigint], boolean>,
  'deleteNotification' : ActorMethod<[bigint], boolean>,
  'deleteQuestion' : ActorMethod<[bigint], boolean>,
  'deleteTimer' : ActorMethod<[bigint], boolean>,
  'filterTransactions' : ActorMethod<[TransactionFilter], Array<Transaction>>,
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  'getAppBranding' : ActorMethod<[], AppBranding>,
  'getBankAccountDetails' : ActorMethod<[], [] | [BankAccountDetails]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChallengeLeaderboard' : ActorMethod<[], Array<[string, bigint]>>,
  'getConnectedAppInfo' : ActorMethod<[], ConnectedAppInfo>,
  'getContentFile' : ActorMethod<[bigint], [] | [ContentFile]>,
  'getCoupon' : ActorMethod<[string], [] | [Coupon]>,
  'getCouponUsageHistory' : ActorMethod<[string], Array<CouponUsage>>,
  'getCourse' : ActorMethod<[bigint], [] | [Course]>,
  'getCourseCompletionTimeSeries' : ActorMethod<
    [bigint],
    Array<TimeSeriesDataPoint>
  >,
  'getCourseStats' : ActorMethod<[string], [] | [CourseStats]>,
  'getHomepageContent' : ActorMethod<[], HomepageContent>,
  'getMockTest' : ActorMethod<[bigint], [] | [MockTest]>,
  'getMyRewards' : ActorMethod<[], [] | [ReferralReward]>,
  'getNotification' : ActorMethod<[bigint], [] | [Notification]>,
  'getNotificationHistory' : ActorMethod<[], Array<NotificationHistory>>,
  'getPaymentMethod' : ActorMethod<[string], [] | [PaymentMethodConfig]>,
  'getRazorpayConfig' : ActorMethod<[], [] | [RazorpayConfig]>,
  'getRetentionRates' : ActorMethod<[], RetentionStats>,
  'getRevenueStats' : ActorMethod<[], RevenueStats>,
  'getRevenueTimeSeries' : ActorMethod<[bigint], Array<TimeSeriesDataPoint>>,
  'getSentNotifications' : ActorMethod<[], Array<Notification>>,
  'getStudentProgress' : ActorMethod<[string], Array<StudentProgress>>,
  'getSyncEndpoint' : ActorMethod<[], SyncEndpoint>,
  'getTestLeaderboard' : ActorMethod<[bigint], Array<TestResult>>,
  'getTestResult' : ActorMethod<[UserId, bigint], [] | [TestResult]>,
  'getTopCoursesByEnrollment' : ActorMethod<[bigint], Array<CourseEnrollment>>,
  'getTransaction' : ActorMethod<[bigint], [] | [Transaction]>,
  'getUser' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUserDetail' : ActorMethod<
    [UserId],
    [] | [[UserProfile, Array<UserProgress>]]
  >,
  'getUserProgress' : ActorMethod<[UserId, bigint], [] | [UserProgress]>,
  'getUserSignupTimeSeries' : ActorMethod<[bigint], Array<TimeSeriesDataPoint>>,
  'getWithdrawalRequest' : ActorMethod<[bigint], [] | [WithdrawalRequest]>,
  'getWithdrawalStats' : ActorMethod<[], WithdrawalStats>,
  'gradeAndSubmit' : ActorMethod<
    [bigint, Array<UserAnswer>, bigint],
    TestResult
  >,
  'grantCourseAccess' : ActorMethod<[UserId, bigint], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllRewards' : ActorMethod<[], Array<ReferralReward>>,
  'listAuditLog' : ActorMethod<[], Array<AuditLogEntry>>,
  'listChallenges' : ActorMethod<[], Array<StudyChallenge>>,
  'listContentFiles' : ActorMethod<[], Array<ContentFile>>,
  'listCoupons' : ActorMethod<[], Array<Coupon>>,
  'listCourseStats' : ActorMethod<[], Array<CourseStats>>,
  'listCourses' : ActorMethod<[], Array<Course>>,
  'listDailyQuestions' : ActorMethod<[], Array<DailyQuestion>>,
  'listFailedTransactions' : ActorMethod<[], Array<Transaction>>,
  'listLessons' : ActorMethod<[bigint], Array<Lesson>>,
  'listMockTests' : ActorMethod<[], Array<MockTest>>,
  'listModules' : ActorMethod<[bigint], Array<CourseModule>>,
  'listMotivationalMessages' : ActorMethod<[], Array<MotivationalMessage>>,
  'listNotifications' : ActorMethod<[], Array<Notification>>,
  'listPaymentMethods' : ActorMethod<[], Array<PaymentMethodConfig>>,
  'listQuestions' : ActorMethod<[bigint], Array<Question>>,
  'listReferralCodes' : ActorMethod<[], Array<ReferralCode>>,
  'listSyncLogs' : ActorMethod<[], Array<SyncLogEntry>>,
  'listTimers' : ActorMethod<[], Array<CountdownTimer>>,
  'listTransactions' : ActorMethod<[], Array<Transaction>>,
  'listTransactionsPaginated' : ActorMethod<
    [TransactionFilter, bigint, bigint],
    PaginatedTransactions
  >,
  'listUserProgress' : ActorMethod<[UserId], Array<UserProgress>>,
  'listUserTransactions' : ActorMethod<[UserId], Array<Transaction>>,
  'listUsers' : ActorMethod<
    [[] | [string], [] | [UserStatus], bigint, bigint],
    Array<UserProfile>
  >,
  'listWithdrawalRequests' : ActorMethod<
    [WithdrawalFilter, bigint, bigint],
    PaginatedWithdrawals
  >,
  'publishCourse' : ActorMethod<[bigint, boolean], boolean>,
  'recordChallengeCompletion' : ActorMethod<[bigint], bigint>,
  'recordPdfDownload' : ActorMethod<[string, string, string], undefined>,
  'recordSyncLog' : ActorMethod<[SyncLogEntry], undefined>,
  'recordVideoView' : ActorMethod<[string, string, string], undefined>,
  'refundTransaction' : ActorMethod<[bigint, string], boolean>,
  'regenerateReferralCode' : ActorMethod<[bigint], [] | [bigint]>,
  'removePdfFileFromLesson' : ActorMethod<[string, string], boolean>,
  'removeVideoFileFromLesson' : ActorMethod<[string, string], boolean>,
  'reorderLessonFiles' : ActorMethod<
    [string, Array<string>, Array<string>],
    boolean
  >,
  'reviewTestAnswers' : ActorMethod<
    [bigint, Array<UserAnswer>],
    Array<ReviewItem>
  >,
  'revokeCourseAccess' : ActorMethod<[UserId, bigint], boolean>,
  'revokeReferralCode' : ActorMethod<[bigint], boolean>,
  'sendNotification' : ActorMethod<[bigint], boolean>,
  'setAppBranding' : ActorMethod<[AppBranding], undefined>,
  'setBankAccountDetails' : ActorMethod<[BankAccountDetails], undefined>,
  'setContentFilePublished' : ActorMethod<[bigint, boolean], boolean>,
  'setHomepageContent' : ActorMethod<[HomepageContent], undefined>,
  'setPaymentMethodEnabled' : ActorMethod<[string, boolean], boolean>,
  'setRazorpayConfig' : ActorMethod<[RazorpayConfig], undefined>,
  'setSyncEndpoint' : ActorMethod<[string], undefined>,
  'setUserStatus' : ActorMethod<[UserId, UserStatus], boolean>,
  'submitTestResult' : ActorMethod<[TestResult], undefined>,
  'toggleCouponStatus' : ActorMethod<[string], boolean>,
  'topReferrers' : ActorMethod<[], Array<ReferralReward>>,
  'updateChallenge' : ActorMethod<[StudyChallenge], boolean>,
  'updateConnectedAppInfo' : ActorMethod<[string, string], undefined>,
  'updateContentFile' : ActorMethod<[ContentFile], boolean>,
  'updateCoupon' : ActorMethod<[Coupon], boolean>,
  'updateCourse' : ActorMethod<[Course], boolean>,
  'updateDailyQuestion' : ActorMethod<[DailyQuestion], boolean>,
  'updateLesson' : ActorMethod<[Lesson], boolean>,
  'updateMockTest' : ActorMethod<[MockTest], boolean>,
  'updateModule' : ActorMethod<[CourseModule], boolean>,
  'updateNotification' : ActorMethod<[Notification], boolean>,
  'updateQuestion' : ActorMethod<[Question], boolean>,
  'updateTransactionStatus' : ActorMethod<[bigint, PaymentStatus], boolean>,
  'updateWithdrawalStatus' : ActorMethod<
    [bigint, WithdrawalStatus, [] | [string]],
    boolean
  >,
  'upsertPaymentMethod' : ActorMethod<[PaymentMethodConfig], undefined>,
  'upsertProgress' : ActorMethod<[UserProgress], undefined>,
  'upsertUser' : ActorMethod<[UserProfile], undefined>,
  'useCoupon' : ActorMethod<[string, string], boolean>,
  'useReferralCode' : ActorMethod<[string, UserId], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];